sudo: required
services:
  - docker

before_install:
  - docker build -t prasad/react-test -f ./client/Dockerfile.dev ./clinet

script:
  - docker run prasad/react-test nmp test -- --coverage

after_success:
  - docker  build -t prasad/multi-client ./client
  - docker  build -t prasad/multi-nginx ./nginx
  - docker  build -t prasad/multi-server ./server
  - docker  build -t prasad/multi-worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub

  - docker push prasad/multi-client
  - docker push prasad/multi-nginx
  - docker push prasad/multi-server
  - docker push prasad/multi-worker


